on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t elycheikhsidahmedely23/devops:latest .

      - name: Push Docker image
        env:
          DOCKER_PASSWORD: ${{ secrets.DEVOPS }}
          DOCKER_USERNAME: elycheikhsidahmedely23
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push elycheikhsidahmedely23/dev



