on: [push]

jobs:
  jublish_images:
    runs-on : ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: build image
        run: docker build -t elycheikhsidahmedely23/DevOps:latest .

      - name: push image to docker hub 
        run: |
          echo ${{ secrets.DEVOPS }} | docker login -u elycheikhsidahmedely23 --password-stdin
          docker push elycheikhsidahmedely23/DevOps:latest








