on:
  push:
    branches:
      - main

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t elycheikhsidahmedely23/devops:latest .

      - name: Push Docker image
        run: |
          echo $DOCKER_PASSWORD | docker login -u elycheikhsidahmedely23  --password-stdin
          docker push elycheikhsidahmedely23/devops



