on: [push]
jobs:
  bublish_images:
    runs_on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4


      - name: build image
        run: docker build -t elycheikhsidahmedely23/devops:latest
      - name: push image to docker 
        run: |
           echo ${{ secrets.DEVOPS }} | docker login -u docker login -u elycheikhsidahmedely23 --password-stdin
           docker push elycheikhsidahmedely23/DevOps:latest
          